### ISSUE TITLE
Support Junit 5

### ISSUE THREAD

**Issue by Goooler** [cashapp/burst#35]
```
No ParameterResolver registered for parameter [io.github.goooler.exporter.IntegrationTest$TestCase arg0] in constructor [public io.github.goooler.exporter.IntegrationTest(io.github.goooler.exporter.IntegrationTest$TestCase)].
org.junit.jupiter.api.extension.ParameterResolutionException: No ParameterResolver registered for parameter [io.github.goooler.exporter.IntegrationTest$TestCase arg0] in constructor [public io.github.goooler.exporter.IntegrationTest(io.github.goooler.exporter.IntegrationTest$TestCase)].
	at java.util.Optional.orElseGet(Optional.java:267)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
```

**Comment by swankjesse** [comment]
Possibly accidentally fixed by making test classes `ABSTRACT` here: 
https://github.com/cashapp/burst/pulls

But we should add a JUnit 5 integration test to validate that.
